"""The minimal shared agents file — the always-on anchor, one source, materialized on fold.

The anchor is authored once at `AGENTS.md` (the open, harness-neutral convention), and the harness
that loads it is reached by a **derived bridge**, not by assuming it reads `AGENTS.md` directly. Stock
Claude Code reads `CLAUDE.md`, not `AGENTS.md` (Anthropic memory doc, verified 2026-06-22: *"Claude Code
reads `CLAUDE.md`, not `AGENTS.md`"*), so a bare `AGENTS.md` would load as **nothing**. The
Anthropic-sanctioned bridge is a `CLAUDE.md` that imports the anchor with `@AGENTS.md`, and that bridge
is itself a derived channel (`bridge_materialize` below) — one anchor, the import the only second file,
re-rendered by the fold so it cannot drift. *(The dropped symlink reinstated as a derived import; the
harness fact corrected.)*

The field evidence is blunt about what such a file is worth — context files *reduce* task success rates
versus no repository context, while raising inference cost by over 20% (arXiv:2602.11988, ETH/SRI 2026) —
so the operator set it to a single **minimal shared anchor, non-inferable content only**: the check
command, the build/hand-back convention, and a pointer to the skills, where the real specialization
lives. Nothing here a capable agent could infer from the tree; no identity prose, no per-capability
requirements.

It is one more derived channel: generated from source, never hand-edited, regenerated by
the fold, so a committed `AGENTS.md` can no more drift from the system than the skills can. The single
source is split by what each part actually is: the operational lines are this module's small authored
residue (the genuinely non-inferable bits — the exact check command, the cross-role hand-back
convention), and the **skills index is derived from the channels' own registries**, so adding a skill
lists it here automatically with no second copy to maintain.

The honest limit: the harness asserts the scaffold — the anchor is minimal, its skills
index is derived, the bridge lands where the harness reads, and the fold materializes all of it — but
whether the file *helps* a live model (the A/B the field warns to run before leaning on it) is a
measurement, not a check, and is recorded as such rather than faked. The final confirmation that a live
`claude -p` session actually loads the bridge is the operator's watched evidence, not a thing the fold
can assert.
"""
from __future__ import annotations

import os

from . import tree

PATH = "AGENTS.md"
BRIDGE_PATH = "CLAUDE.md"  # the harness-specific bridge: Claude Code reads this, not AGENTS.md
CHECK = "python3 -m engine --check"  # the textbook non-inferable detail — the exact harness command


def agents_file(root: str | None = None) -> str:
    """The anchor's text: a one-paragraph orientation (who this file is for), then the non-inferable
    operational lines, then the skills index derived from the registry. The only authored content is the
    orientation and the operational residue — the skills list is single-sourced from the channels'
    registries, so a new skill appears here by construction, never by hand.

    The orientation paragraph is the dogfooding tax: hypercore's runtime root *is* its own source repo,
    so this auto-loaded anchor is read both by the architect/worker the system spawns (its intended
    audience) **and** by any session working *on* hypercore. Without a word, the latter is misdirected
    into a runtime role; the orientation routes it to the README instead, so the always-on file helps a
    fresh session rather than fighting it."""
    return (
        "# hypercore — the operating anchor\n\n"
        "**Working *on* hypercore** — a person, or a coding assistant editing this repo — rather than "
        "running as the system's own architect or worker? This file is not your instructions: read "
        "`README.md`, then `intent.md` and `spec/`; run the acceptance harness with "
        f"`{CHECK}` and the operator interface with `python3 -m engine`. The rest below is the runtime "
        "**role anchor** — the minimal always-on context the system loads into the architect and the "
        "fenced worker. It is deliberately minimal: only the non-inferable operational lines, with the "
        "specialization in the skills and the living spec, not here.\n\n"
        "## Operating (the runtime roles)\n\n"
        "- **Build deep, hand back for the machine.** Build deep up front — load the `depth` skill; "
        "depth is judgment, never a line count to trim to. A worker's proof is its own capability's "
        "scenarios going red→green over its fence, run by the gate; it authors no loop, and the "
        "whole-tree scan is the architect's, not its hand-back bar. Hand back a complete result written "
        "for the machine, never for the operator — the architect authors every operator-facing word.\n"
        f"- **Check is the architect's fold gate.** `{CHECK}` runs the acceptance harness over the "
        "merged result; nothing folds that does not pass it. Its whole-tree depth and complexity review "
        "is the architect's safeguard over the build — resolve a long module by deepening it or "
        "recording the accepted length, never by trimming it to pass.\n\n"
        "## Skills — the specialization, loaded on demand\n\n"
        "Load the one the task in front of you routes to (`skills/<name>/SKILL.md`):\n\n"
        + _skills_index() + "\n"
    )


def materialize(root: str | None = None) -> str:
    """Write the anchor — the fold's render step for this channel (`channels`). Returns the `AGENTS.md`
    path. Idempotent, like every materializer, so even a trivial fold safely keeps it current."""
    path = os.path.join(root or tree._root(), PATH)
    tree.atomic_write(path, agents_file(root))
    return path


def bridge(root: str | None = None) -> str:
    """The Claude Code bridge file's text: an `@AGENTS.md` import and nothing else. Stock Claude Code
    auto-loads `CLAUDE.md`, not `AGENTS.md`, and the Anthropic-sanctioned way to make it read an existing
    anchor is a `CLAUDE.md` that imports it (`@AGENTS.md`) — so the anchor stays the one authored source
    and this is a pure pointer to it. No content of its own can drift, because it holds no content."""
    return (
        "# hypercore\n\n"
        "<!-- Derived bridge: Claude Code reads CLAUDE.md, not AGENTS.md, so it imports the anchor.\n"
        "     Regenerated by the fold (engine/anchor.py); do not hand-edit. -->\n\n"
        "@AGENTS.md\n"
    )


def bridge_materialize(root: str | None = None) -> str:
    """Write the `CLAUDE.md` bridge — the channel that lands the anchor where Claude Code actually reads
    it. One more derived render the fold runs, idempotent like the rest, so the import can no more drift
    from the anchor than the anchor can from the spec."""
    path = os.path.join(root or tree._root(), BRIDGE_PATH)
    tree.atomic_write(path, bridge(root))
    return path


# ── the skills index: derived from the channels' registries, so it cannot drift ───────────

def _skills_index() -> str:
    """The available skills as a derived list — the architect's methodologies and the worker's `depth`,
    plus the worker's own discipline, all pulled from the one skills registry the skills themselves
    render from (`methodology.METHODOLOGIES`), so the index cannot drift from the set."""
    from . import methodology
    skills = list(methodology.METHODOLOGIES.items())
    return "\n".join(f"- `{name}` — {_first_sentence(desc)}" for name, desc in skills)


def _first_sentence(desc: str) -> str:
    """A skill's description trimmed to its first sentence — the anchor lists skills tersely; the full
    when-to-load lives in each `SKILL.md`'s metadata, the same source this first clause comes from."""
    return desc.split(". ")[0].rstrip(".") + "."
