"""The minimal shared agents file — the always-on anchor, one source, materialized on fold.

Both roles auto-load one always-on file: `AGENTS.md` at the root. The architect's harness (Claude)
reads it directly when no `CLAUDE.md` is present, and OMP reads it natively — so **one file serves
both roles** and the `CLAUDE.md` symlink ADR 0009 §4 first reached for was pure redundancy, dropped
(ADR 0009 §4 amended). The field evidence is blunt about what such a file is worth — even a good one is
marginal and adds ~20% cost, and it *hurts* as a repository overview (arXiv 2602.11988) — so the
operator set it to a single **minimal shared anchor, non-inferable content only**: the check command,
the build/hand-back convention, and a pointer to the skills, where the real specialization lives.
Nothing here a capable agent could infer from the tree; no identity prose, no per-capability requirements.

It is one more derived channel (ADR 0009 §3): generated from source, never hand-edited, regenerated by
the fold, so a committed `AGENTS.md` can no more drift from the system than the skills can. The single
source is split by what each part actually is: the operational lines are this module's small authored
residue (the genuinely non-inferable bits — the exact check command, the cross-role hand-back
convention), and the **skills index is derived from the channels' own registries**, so adding a skill
lists it here automatically with no second copy to maintain.

The honest limit (ADR 0009 §6): the harness asserts the scaffold — the anchor is minimal, its skills
index is derived, and the fold materializes it — but whether the file *helps* a live model (the A/B the
field warns to run before leaning on it) is a measurement, not a check, and is recorded as such rather
than faked.
"""
from __future__ import annotations

import os

from . import graph

PATH = "AGENTS.md"
CHECK = "python3 -m engine --check"  # the textbook non-inferable detail — the exact harness command


def agents_file(root: str | None = None) -> str:
    """The anchor's text: a one-paragraph orientation (who this file is for), then the non-inferable
    operational lines, then the skills index derived from the registry. The only authored content is the
    orientation and the operational residue — the skills list is single-sourced from the channels'
    registries, so a new skill appears here by construction, never by hand.

    The orientation paragraph is the dogfooding tax: hypercore's runtime root *is* its own source repo,
    so this auto-loaded anchor is read both by the architect/worker the system spawns (its intended
    audience) **and** by any session working *on* hypercore. Without a word, the latter is misdirected
    into a runtime role; the orientation routes it to the README instead, so the always-on file helps a
    fresh session rather than fighting it."""
    return (
        "# hypercore — the operating anchor\n\n"
        "**Working *on* hypercore** — a person, or a coding assistant editing this repo — rather than "
        "running as the system's own architect or worker? This file is not your instructions: read "
        "`README.md`, then `intent.md` and `spec/`; run the acceptance harness with "
        f"`{CHECK}` and the operator interface with `python3 -m engine`. The rest below is the runtime "
        "**role anchor** — the minimal always-on context the system loads into the architect and the "
        "fenced worker. It is deliberately minimal: only the non-inferable operational lines, with the "
        "specialization in the skills and the living spec, not here.\n\n"
        "## Operating (the runtime roles)\n\n"
        f"- **Check.** Run the acceptance harness before handing back: `{CHECK}`. It is the "
        "red→green feedback loop; nothing folds that does not pass it.\n"
        "- **Build, and hand back for the machine.** Build behind that loop and hand back a complete "
        "result written for the machine, never for the operator — the architect authors every "
        "operator-facing word.\n\n"
        "## Skills — the specialization, loaded on demand\n\n"
        "Load the one the task in front of you routes to (`skills/<name>/SKILL.md`):\n\n"
        + _skills_index() + "\n"
    )


def materialize(root: str | None = None) -> str:
    """Write the anchor — the fold's render step for this channel (`channels`). Returns the `AGENTS.md`
    path. Idempotent, like every materializer, so even a trivial fold safely keeps it current."""
    path = os.path.join(root or graph._root(), PATH)
    graph.atomic_write(path, agents_file(root))
    return path


# ── the skills index: derived from the channels' registries, so it cannot drift ───────────

def _skills_index() -> str:
    """The available skills as a derived list — the architect's methodologies and the worker's `depth`,
    all pulled from the one skills registry the skills themselves render from (`methodology.METHODOLOGIES`),
    so the index cannot drift from the set."""
    from . import methodology
    skills = list(methodology.METHODOLOGIES.items())
    return "\n".join(f"- `{name}` — {_first_sentence(desc)}" for name, desc in skills)


def _first_sentence(desc: str) -> str:
    """A skill's description trimmed to its first sentence — the anchor lists skills tersely; the full
    when-to-load lives in each `SKILL.md`'s metadata, the same source this first clause comes from."""
    return desc.split(". ")[0].rstrip(".") + "."
