"""Slice 12 — item 2, build step 4: the architect's methodology skills (ADR 0009 §5.4).

Acceptance (ADR 0009): the architect's specialization lives in **skills**, each rendered from its
capability spec slice and regenerated by the fold — never hand-copied. Step 2 (slice 11) built the
materialize-on-fold registry with the worker's `depth` skill as its first target; this step adds the
architect's methodology skills (`design-it-twice`, `architecture-review`) as more renders that plug
into the same registry, single-sourced from `spec/<cap>/spec.md`.

Driven, like slices 10–11, over a **planted** capability slice (a controlled source carrying a
sentinel in its preamble and a sentinel requirement) so a derived skill must reproduce THIS slice.

1. **derived render** — the skill renders its slice's overview and disciplines, carries the discipline
   *statements* but leaves the scenarios in the slice, and points back to the slice as its source;
2. **the fold materializes it** — a fold regenerates the methodology skill on disk (the channels
   registry), and the artifact is the pure render;
3. **drift is impossible** — editing the slice and folding again re-renders the skill to match;
4. **every architect methodology is registered** — each one materializes through the channels registry.

`grilling`/coherence are deliberately absent — they are requirements inside `conversation`, not a
standalone slice; skilling them is recorded as a follow-up, not hacked into this render.
"""
from __future__ import annotations

import os

from .harness import ok


def check(root: str) -> None:
    from .. import channels, delta, depth, graph, methodology, spec

    print("\nslice 12 — acceptance check  (the architect's methodology skills, single-sourced)\n")

    CAP = "design-it-twice"
    NONCE = "ZQX-methodology"
    planted = (
        f"# {CAP}\n\n"
        f"Planted methodology overview — {NONCE}: how the architect designs a thing twice.\n\n"
        "### Requirement: a planted discipline the architect holds\n"
        f"The architect MUST hold the planted discipline — {NONCE}-stmt.\n"
        "#### Scenario: the discipline holds\n"
        "- WHEN a planted decision is judged\n"
        "- THEN the planted discipline is applied\n"
    )
    src = spec.cap_path(CAP, root)
    graph.atomic_write(src, planted)

    art = os.path.join(root, methodology.skill_path(CAP))
    if os.path.isfile(art):
        os.remove(art)

    # ── 1. the skill is a derived render of its slice ─────────────────────────────────────
    sk = methodology.skill(CAP, root)
    ok(sk.startswith("---") and f"name: {CAP}" in sk,
       "the methodology skill is a progressive-disclosure SKILL.md — metadata, then the methodology")
    ok(NONCE in sk and "a planted discipline the architect holds" in sk and NONCE + "-stmt" in sk,
       "it renders the planted slice's overview and the discipline's statement — derived, single-sourced")
    ok("a planted decision is judged" not in sk,
       "it carries the discipline statements but leaves the scenarios in the slice — progressive disclosure")
    ok(f"spec/{CAP}/spec.md" in sk,
       "it points back to its spec slice for the full requirements — the single source")

    # ── 2. the fold materializes it through the channels registry ──────────────────────────
    delta.fold(delta.parse("# delta — trivial (no behavior change)"), root)
    ok(os.path.isfile(art) and open(art, encoding="utf-8").read() == sk,
       "the fold materializes the methodology skill — registered in the channels registry, a pure render")

    # ── 3. drift is impossible: edit the slice, fold again, the skill follows ──────────────
    graph.atomic_write(src, planted.replace(NONCE, "EDITED-" + NONCE))
    delta.fold(delta.parse("# delta — trivial (no behavior change)"), root)
    ok("EDITED-" + NONCE in open(art, encoding="utf-8").read(),
       "a later fold re-renders the skill from the changed slice — a committed channel cannot drift")

    # ── 4. every architect methodology is registered and materializes ──────────────────────
    paths = channels.materialize(root)
    ok(set(methodology.METHODOLOGIES) >= {"design-it-twice", "architecture-review"},
       "both clean standalone architect methodologies are registered (grilling deferred — it has no slice)")
    for cap in methodology.METHODOLOGIES:
        p = os.path.join(root, methodology.skill_path(cap))
        ok(os.path.isfile(p) and any(os.path.samefile(p, q) for q in paths),
           f"the {cap} skill materializes through the channels registry")
    ok(depth.materialize in channels.CHANNELS and len(channels.CHANNELS) >= 3,
       "the worker's depth skill and the architect's methodology skills share the one fold-driven registry")
