"""Slice 11 — item 2, build step 2: materialize-on-fold (role-assembly step 2).

Acceptance: single-sourcing is a derived render *regenerated by the fold*. The fold gains
a render step that re-materializes the static channels (skills, the agents file) from the spec, so a
committed artifact can no more drift from its source than the spec can drift from a folded delta. Step
1 (slice 10) single-sourced `depth.materialize` and proved the artifact is a pure render; this step
wires that render into the fold — `channels.materialize`, the registry steps 3–4 plug into — and pins
that **the fold itself** keeps the channels current.

Driven, like slice 10, over a **planted** spec/depth.md (a controlled source carrying a sentinel) so a
derived artifact must reproduce THIS source. The fold writes the artifact into the root, so the proof
is direct: fold, then read what landed on disk.

1. **the fold materializes** — a fold (even a trivial one) regenerates the depth skill on disk from
   the planted source; the artifact is the pure render, nothing hand-authored;
2. **drift is impossible** — editing the source and folding again re-renders the artifact to match;
3. **the registry is the seam** — `channels.materialize` regenerates every static channel and returns
   the paths, the one place steps 3–4 (agents file, architect skills) append to;
4. **a real behavior fold carries it too** — a delta that changes the spec also re-renders the
   channels in the same act, committed together.
"""
from __future__ import annotations

import os
import subprocess

from .harness import ok


def check(root: str) -> None:
    from .. import channels, delta, tree, methodology, spec

    print("\nslice 11 — acceptance check  (materialize-on-fold: derived channels follow the spec)\n")

    # Plant a controlled depth source carrying a sentinel — the slice-10 idiom. A fold-rendered
    # artifact must reproduce THIS source, not a frozen copy and not the package fallback.
    NONCE = "ZQX-fold-rendered"
    planted = (
        "# depth\n\n"
        f"Planted depth overview — {NONCE}: build deep modules.\n\n"
        "### Requirement: a planted depth discipline\n"
        f"The worker MUST hold the planted discipline — {NONCE}-stmt.\n"
        "#### Scenario: a module is built\n"
        "- WHEN a worker builds a module\n- THEN the planted discipline applies\n"
    )
    src = spec.cap_path("depth", root)               # spec/depth.md — the capability slice
    tree.atomic_write(src, planted)

    # Remove any prior artifact so the proof is that the FOLD created it, not that it lingered.
    art = os.path.join(root, methodology.skill_path("depth"))
    if os.path.isfile(art):
        os.remove(art)

    # ── 1. the fold materializes the channel from source ──────────────────────────────────
    delta.fold(delta.parse("# delta — trivial (no behavior change)"), root)
    ok(os.path.isfile(art),
       "the fold materialized the depth skill artifact on disk — the render step the fold gained")
    rendered = open(art, encoding="utf-8").read()
    ok(NONCE in rendered and NONCE + "-stmt" in rendered,
       "the artifact is rendered from the planted depth slice — derived by the fold, not hand-authored")
    ok(rendered == methodology.skill("depth", root),
       "the materialized artifact is exactly the render of its source — pure derived output, nothing edited")

    # ── 2. drift is impossible: edit the source, fold again, the artifact follows ──────────
    tree.atomic_write(src, planted.replace(NONCE, "EDITED-" + NONCE))
    delta.fold(delta.parse("# delta — trivial (no behavior change)"), root)
    ok("EDITED-" + NONCE in open(art, encoding="utf-8").read(),
       "a later fold re-renders the artifact from the changed source — a committed channel cannot drift")

    # ── 3. the registry is the seam steps 3–4 plug into ───────────────────────────────────
    paths = channels.materialize(root)
    ok(channels.CHANNELS and any(os.path.samefile(p, art) for p in paths),
       "the depth skill is one of channels.materialize's re-renders — the registry the fold drives")
    ok(len(channels.CHANNELS) == len(methodology.METHODOLOGIES) * len(methodology.SKILL_DIRS) + 2,
       "the registry is every capability skill per mirrored location plus the anchor and its CLAUDE.md "
       "bridge — one flat fold-driven set")

    # ── 4. a real behavior fold carries the render step too (not only trivial deltas) ──────
    tree.atomic_write(src, planted.replace(NONCE, "REALFOLD-" + NONCE))
    delta.fold(delta.parse(
        "# delta — a real behavior change\n\n"
        "## ADDED — demo\n"
        "### Requirement: the demo capability exists\n"
        "The demo MUST exist.\n"
        "#### Scenario: it exists\n- WHEN asked\n- THEN it is there\n"), root)
    ok("REALFOLD-" + NONCE in open(art, encoding="utf-8").read(),
       "a spec-changing fold re-renders the channels in the same act — the render step runs on every fold")
    log = subprocess.run(["git", "log", "--oneline"], cwd=root,
                         capture_output=True, text=True).stdout
    ok("fold:" in log,
       "the fold commits the spec change and its re-rendered channels together — one durable act")
